/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_layer_i2c_I2cNative */

#ifndef _Included_I2cNative
#define _Included_I2cNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    openBus
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_openBus
        (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    closeBus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_closeBus
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    writeByte
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_writeByte
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    writeWord
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_writeWord
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    readWord
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_readWord
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    readAllBytes
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_layer_i2c_I2cNative_readAllBytes
        (JNIEnv *, jclass, jint, jint);

JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_readRawBytes
        (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    readBlockData
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_readBlockData
        (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_write
        (JNIEnv *env, jclass jcl, jint fd, jint value);
        
/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    switchDeviceAddress
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_switchDeviceAddress
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    scanAddress
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_scanAddress
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    recoverBus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_recoverBus
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_layer_i2c_I2cNative
 * Method:    setSchedIdle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_layer_i2c_I2cNative_setSchedIdle
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif